import { Todo } from "@/app/home/_types/todo-type";

export const todoMocks: Todo[] = [
  {
    todoId: 145,
    icon: "ICON_3",
    title: "티모 하이와프 작업하기",
    completed: false,
    durationSeconds: 7200,
    priority: "HIGH",
    tag: { tagId: 3, name: "업무" },
    hasMemo: false,
    isRepeated: true,
    timerStatus: "RUNNING",
    sortOrder: 0,
    subtaskTotalCount: 2,
    subtaskCompletedCount: 1,
  },
  {
    todoId: 146,
    icon: "ICON_1",
    title: "앱잼 1차 과제 제출",
    completed: false,
    durationSeconds: 5400,
    priority: "URGENT",
    tag: { tagId: 1, name: "과제" },
    hasMemo: true,
    isRepeated: false,
    timerStatus: "STOPPED",
    sortOrder: 1,
    subtaskTotalCount: 0,
    subtaskCompletedCount: 0,
  },
  {
    todoId: 147,
    icon: "ICON_2",
    title: "운동하기",
    completed: true,
    durationSeconds: 1800,
    priority: "LOW",
    tag: { tagId: 4, name: "루틴" },
    hasMemo: false,
    isRepeated: true,
    timerStatus: "STOPPED",
    sortOrder: 2,
    subtaskTotalCount: 0,
    subtaskCompletedCount: 0,
  },
  {
    todoId: 148,
    icon: "ICON_4",
    title: "독서 30분",
    completed: false,
    durationSeconds: 1800,
    priority: "MEDIUM",
    tag: { tagId: 5, name: "자기계발" },
    hasMemo: true,
    isRepeated: false,
    timerStatus: "STOPPED",
    sortOrder: 3,
    subtaskTotalCount: 1,
    subtaskCompletedCount: 0,
  },
];
